# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171210_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinstance',
            name='team_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='팀 번호'),
        ),
        migrations.AlterField(
            model_name='studentinstance',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.DateModel'),
        ),
    ]
